name: wger
description: Self hosted workout, nutrition and weight manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# Note: these versions are set automatically during build by the android-release.yml
# github action, the current versions are ignored.
#   - the version number is taken from the git tag vX.Y.Z
#   - the build number is computed by reading the last one from the play store
#     and increasing by one
version: 1.8.2+70

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^5.0.0
  clock: ^1.1.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  equatable: ^2.0.7
  fl_chart: ^0.69.2
  flex_color_scheme: ^8.1.1
  flex_seed_scheme: ^3.5.1
  flutter_html: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  flutter_svg_icons: ^0.0.1
  flutter_typeahead: ^5.2.0
  flutter_zxing: ^2.0.0
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http: ^1.2.2
  image_picker: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  multi_select_flutter: ^4.1.3
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.4
  rive: ^0.13.20
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.31
  table_calendar: ^3.0.8
  url_launcher: ^6.3.1
  version: ^3.0.2
  video_player: ^2.9.5
  logging: ^1.3.0
  flutter_riverpod: ^2.6.1

#dependency_overrides:
#  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  cider: ^0.2.7
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  network_image_mock: ^2.1.1
  shared_preferences_platform_interface: ^2.0.0

  # Script to read out unused translations
  #translations_cleaner: ^0.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/muscles/
    - assets/images/muscles/main/
    - assets/images/muscles/secondary/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  generate: true
