name: wger
description: Self hosted workout, nutrition and weight manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# Note: these versions are set automatically during build by the android-release.yml
# github action, the current versions are ignored.
#   - the version number is taken from the git branch release/x.y.z
#   - the build number is computed by reading the last one from the play store and increased by one
version: 1.5.1+28

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  android_metadata: ^0.2.1
  camera: ^0.10.0
  charts_flutter: ^0.12.0
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_calendar_carousel: ^2.4.1
  flutter_html: ^2.1.2
  flutter_typeahead: ^4.1.1
  font_awesome_flutter: ^10.3.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  version: ^3.0.2
  package_info: ^2.0.2
  provider: ^6.0.4
  rive: ^0.10.0
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.8
  url_launcher: ^6.1.7
  flutter_barcode_scanner: ^2.0.0
  video_player: ^2.4.9
  flutter_staggered_grid_view: ^0.6.2
  carousel_slider: ^4.2.0
  multi_select_flutter: ^4.1.3
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  network_image_mock: ^2.1.1
  flutter_lints: ^2.0.1
  cider: ^0.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets_dev/logo.png"
  adaptive_icon_background: "#2a4c7d"
  adaptive_icon_foreground: "assets_dev/logo_adaptive.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/muscles/
    - assets/images/muscles/main/
    - assets/images/muscles/secondary/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  generate: true
